fdsaGRgr MNBMNBMNBMNBMNBMNB\JNBREKNVE,Ffrom turtle import *
ps = textinput("blah","co chceš sakra za tvar ????????????????????????? ")
if ps == ("ps"):
    for i in range(1):
      forward(5)
      left(90)
      forward(25)
      right(90)
      color("green")
      begin_fill()
      forward(15)
      left(135)
      forward(15)
      right(135)
      forward(10)
      left(135)
      forward(25)
      left(90)
      forward(25)
      left(135)
      forward(10)
      right(135)
      forward(15)
      left(135)
      forward(15)
      end_fill()
      color("black")
      right(90)
      forward(25)
      penup()
      forward(20)
      pendown()


exitonclick()