from turtle import *
sd = textinput("blah", "co chceš sakra za tvar ????????????????????????? ")
if sd == ("sd"):
    #dum
    left(135)
    forward(21)
    left(90)
    forward(8)
    right(135)
    forward(10)
    left(135)
    forward(5)
    left(45)
    forward(10)
    right(45)
    forward(8)
    left(135)
    forward(30)
    right(90)
    forward(30)
    right(90)
    forward(30)
    right(90)
    forward(30)